Course box
Nauc-me-IT/website pull request #10
Opened 2022-06-20 15:20 UTC by pegak

Fixes #7.

2022-06-20 20:46 UTC, xhemalov requested changes

2022-06-20 20:46 UTC, xhemalov commented on app/components/CourseBox.tsx
> +        side === "left" ? "md:flex-row" : "md:flex-row-reverse"
I do not understand why there is `flex-col` and then `flex-row`.

2022-06-20 20:46 UTC, xhemalov commented on app/components/CourseBox.tsx
> +      <img className={`${side === "left" ? "mr-12" : "ml-12"}`} src={image} alt=''></img>
Alt is empty.

2022-06-20 21:20 UTC, pegak commented on app/components/CourseBox.tsx
> +        side === "left" ? "md:flex-row" : "md:flex-row-reverse"
`flex-col` is for mobiles and `flex-row` || `flex-row-reverse` are from medium breakpoint.

2022-06-20 21:20 UTC, pegak commented on app/components/CourseBox.tsx
> +      <img className={`${side === "left" ? "mr-12" : "ml-12"}`} src={image} alt=''></img>
Great reminder, I'll fix that!

2022-06-21 20:21 UTC, xhemalov approved these changes

2022-06-21 20:34 UTC, merged